### PR TITLE
Fix text logging to restored experiment

### LINKED ISSUE #105: Experiment state and stdout channel do not update when resuming an experiment
Hi,

Sending metrics when resuming an experiment works fine. However the experiment state does not change from "succeeded" to "running". And neither does it log system information (cpu/gpu information) or stdout when resuming an experiment. Code example:

```
import time
import neptune
from neptune.sessions import Session

# Initialize experiment
neptune.init(project_qualified_name='Test/project')
experiment = neptune.create_experiment(name='test')
experiment_id = experiment.id

# Send metrics
for i in range(10):
    time.sleep(2)
    print('logging this to STDOUT channel.')
    experiment.send_metric('iter', i)
    
experiment.stop()

# Resume experiment
session = Session()
project = session.get_project(project_qualified_name='Test/project')
experiment = project.get_experiments(id=experiment_id)[0]

# Send metrics
for i in range(10):
    time.sleep(2)
    print('Unable to log this to STDOUT channel.')
    experiment.send_metric('iter', 3*i)

experiment.stop()
```

### PR DESCRIPTION
**Pull request by wjaskowski**
Now when the experiment is restored from neptune server, you can log text
(stdout, stderr, logger) without the fear that the x values will be
the same as the old ones and will be discarded. (see the rationale:
https://spectrum.chat/neptune-community/general/continuing-an-interrupted-experiment~e9fff5f8-c322-48fc-a84f-2ece82e5c630)

Fixes #105

### CODE REVIEW

**Comment by kamil-kaczmarek** [comment]
Hey @wjaskowski thanks for the PR

@pitercl - can you take a look?

**Comment by pitercl** [comment]
Hi @wjaskowski! Thank you for this PR. I understand the problem you're solving here.

I have some reservations about calling backend every time this class is instantiated, but I think the impact is negligible.

Please, fix the implementation for Python 2.7 (which, unfortunately, we still need to support), and I'll merge it :)

**Comment by kamil-kaczmarek** [comment]
Hey @wjaskowski once again thanks for the PR.

As I understand form @pitercl he is willing to merge it. However, some tests are failing. Would you mind to fix them, so that we can merge it? If you need any help please let us know here.

Thanks!
Kamil

**Comment by wjaskowski** [comment]
Sorry, I have had no time recently. Could you point me how to run the tests
to see what is failing?

**Comment by pitercl** [comment]
That's no problem.

First of all, you can see the tests that fail on Travis here: 
https://travis-ci.org/neptune-ml/neptune-client/builds/621092359?utm_source=github_status&utm_medium=notification

But if you want to run them locally, create a virtual env and run:
```sh
pip install -r requirements.txt
pip install -r test_requirements.txt
make tests
```

Local tests are executed on Python 2.7, 3.5, 3.6.

**Comment by wjaskowski** [comment]
I have found some workarounds for python 2.7 (https://stackoverflow.com/questions/51913210/python-script-with-timezone-fails-when-back-ported-to-python-2-7). Which one do you prefer?

**Comment by pitercl** [comment]
If I understand the problem correctly, we may get away with the following approach:
```py
self._time_started = experiment.get_system_properties()['created']
...

x=(datetime.now(tz=self._time_started.tzinfo) - self._time_started).total_seconds() * 1000
```

What do you think?

**Comment by wjaskowski** [comment]
Some magic in tests doesn't work now...

**Comment by pitercl** [comment]
Ok, thanks for taking it this far. Leave the rest to us - we'll fix it this week.

**Pull request merged**
